services:
  node:
    image: refinedev/node:18
    ports:
      - 5001:5001
      - 5173:5173
    expose:
      - 5173
      - 5001
    volumes:
      - ./:/app/refine
    working_dir: /app/refine
#    env_file:
#      - .env
    command:
#      - npm
#      - install
#      - &&
      - npm
      - run
      - dev
      - --
      - --host
#      - tail
#      - -f
#      - /dev/null
