version: '3.2'

services:
  node:
    image: refinedev/node:18
    ports:
      - 5001:5001
      - 5173:5173
    expose:
      - 5173
      - 5001
    volumes:
      - ./:/app/refine
    working_dir: /app/refine
#    env_file:
#      - .env
    command: tail -f /dev/null
#volumes:
#  db:
